apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: grafana
  namespace: monitoring
  annotations:
    nginx.ingress.kubernetes.io/server-alias: grafana.*
spec:
  rules:
  - host: grafana
    http:
      paths:
      - backend:
          serviceName: grafana
          servicePort: http
        path: /