{
 "title": "blocky",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   { "name": "blocky_url", "label": "blocky API URL", "query": "${VAR_BLOCKY_URL}" }
  ]
 },
 "panels": [
  {
   "title": "State",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 5, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(up{job=\"blocky-metrics\"})"
    }
   ]
  },
  {
   "title": "Blocking",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 7, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "blocky_blocking_enabled" }
   ]
  },
  {
   "title": "Error count 24h",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(blocky_error_total[24h]))"
    }
   ]
  },
  {
   "title": "Queries blocked 24h",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(blocky_response_total{response_type=\"BLOCKED\"}[24h])) / sum(increase(blocky_query_total[24h])) "
    }
   ]
  },
  {
   "title": "Request rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(blocky_query_total[5m])) * 60",
     "legendFormat": "avg requests / min"
    }
   ]
  },
  {
   "title": "Avg response time (all queries) 1h",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 3 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(blocky_request_duration_ms_sum[1h])) / sum(increase(blocky_request_duration_ms_count[1h]))"
    }
   ]
  },
  {
   "title": "Query Count Total 24h",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "ceil(sum(increase(blocky_query_total[24h]))) "
    }
   ]
  },
  {
   "title": "Blacklist entries total",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(blocky_blacklist_cache) / sum(up{job=\"blocky-metrics\"})"
    }
   ]
  },
  {
   "title": "Memory allocated",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 3 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(go_memstats_sys_bytes{job=\"blocky-metrics\"})/sum(up{job=\"blocky-metrics\"})"
    }
   ]
  },
  {
   "title": "request duration (upstream)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(increase(blocky_request_duration_ms_bucket{response_type=\"RESOLVED\"}[24h])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Response Reasons",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 7 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": " sort_desc(sum by (reason) (ceil(increase(blocky_response_total[24h]))))",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Query per Client",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 7 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sort_desc(sum by (client) (ceil(increase(blocky_query_total[24h]))))",
     "legendFormat": "{{ client }}"
    }
   ]
  },
  {
   "title": "Query by type",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 15 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": " sort_desc(sum by (type) (ceil(increase(blocky_query_total[24h]))))",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Blacklist by group",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 15 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "topk(1, blocky_blacklist_cache) by (group)",
     "legendFormat": "{{ group }}"
    }
   ]
  },
  {
   "title": "Response Type",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 15 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": " sort_desc(sum by (response_type) (ceil(increase(blocky_response_total[24h]))))",
     "legendFormat": "{{response_type}}"
    }
   ]
  },
  {
   "title": "Response status",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 15 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": " sort_desc(sum by (response_code) (ceil(increase(blocky_response_total[24h]))))",
     "legendFormat": "{{response_code}}"
    }
   ]
  }
 ]
}