apiVersion: v1
data:
  grafana.ini: W2F1dGhdCmRpc2FibGVfbG9naW5fZm9ybSA9IHRydWUKW2F1dGguYW5vbnltb3VzXQplbmFibGVkID0gdHJ1ZQpvcmdfbmFtZSA9IE1haW4gT3JnLgpvcmdfcm9sZSA9IFZpZXdlcgpbYXV0aC5iYXNpY10KZW5hYmxlZCA9IGZhbHNlCltzZXNzaW9uXQpwcm92aWRlciA9IG1lbW9yeQpbc210cF0KZW5hYmxlZCA9IHRydWUKZnJvbV9hZGRyZXNzID0gbXllbWFpbEBnbWFpbC5jb20KZnJvbV9uYW1lID0gR3JhZmFuYSBBbGVydApob3N0ID0gc210cC1zZXJ2ZXIubW9uaXRvcmluZy5zdmM6MjUKcGFzc3dvcmQgPSAKc2tpcF92ZXJpZnkgPSB0cnVlCnVzZXIgPSAKW3VzZXJzXQpkZWZhdWx0X3RoZW1lID0gbGlnaHQK
kind: Secret
metadata:
  name: grafana-config
  namespace: monitoring
type: Opaque
